export { default as appRouter } from './appRouter'
export { default as authRouter } from './authRouter'
export { default as commentRouter } from './commentRouter'
export { default as postRouter } from './postRouter'
export { default as userRouter } from './userRouter'
export { default as friendRouter } from './friendRouter'