export default {
    // AUTHENTICATION
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',

    // USER ACTION
    GET_ONE: 'GET_ONE',
    GET_ALL: 'GET_ALL',

    // POST ACTION
    GET_ALL_POST: 'GET_ALL_POST',
    DETAIL_POST: 'DETAIL_POST'

}

